language: c
os: linux
dist: bionic
compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install ncurses-dev bc bison flex
  - git clone --branch=master https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

script:
  - export ARCH=um 
  - export KCONFIG_ALLCONFIG=../uml.config
  - cd linux
  - make allnoconfig
  - make -s vmlinux
