language: c
os: linux
dist: bionic
compiler: gcc

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install ncurses-dev bc bison flex
  - mkdir linux
  - wget -q $(wget -qO- https://www.kernel.org | grep downloadarrow_small.png | cut -d'"' -f2)
  - tar --strip-components 1 -xf linux-*.tar.xz -C linux

script:
  - export ARCH=um 
  - export KCONFIG_ALLCONFIG=../uml.config
  - export CPUCOUNT=$(grep -c "^processor" /proc/cpuinfo)
  - cd linux
  - make -s -j${CPUCOUNT} allnoconfig
  - make -s -j${CPUCOUNT} vmlinux
